# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TofuSummary < Formula
  desc "Condensed, readable summaries of OpenTofu/Terraform plans"
  homepage "https://github.com/pablocolson/opentofu-summary"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pablocolson/opentofu-summary/releases/download/v0.1.0/tofu-summary_0.1.0_darwin_amd64.tar.gz"
      sha256 "4cabb74c4fac484acc007a27338e39f4ab88dd018343a248f3355847e6b4620e"

      define_method(:install) do
        bin.install "tofu-summary"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pablocolson/opentofu-summary/releases/download/v0.1.0/tofu-summary_0.1.0_darwin_arm64.tar.gz"
      sha256 "38bb525d645f1fd073d6f3853a153cfee250dba9c259a2f4e0df76a72c995c2e"

      define_method(:install) do
        bin.install "tofu-summary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pablocolson/opentofu-summary/releases/download/v0.1.0/tofu-summary_0.1.0_linux_amd64.tar.gz"
      sha256 "9d9f5fdc734ba8003740db58bb3e804432d53437448dc660e5965577de5728a1"
      define_method(:install) do
        bin.install "tofu-summary"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pablocolson/opentofu-summary/releases/download/v0.1.0/tofu-summary_0.1.0_linux_arm64.tar.gz"
      sha256 "774b4cdd31f3090d37572eba5157db77b6de9c4ba3d43fd1b98a71d99181be6b"
      define_method(:install) do
        bin.install "tofu-summary"
      end
    end
  end

  test do
    system "#{bin}/tofu-summary", "-version"
  end
end
