# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TofuSummary < Formula
  desc "Condensed, readable summaries of OpenTofu/Terraform plans"
  homepage "https://github.com/pablocolson/opentofu-summary"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pablocolson/opentofu-summary/releases/download/v0.1.1/tofu-summary_0.1.1_darwin_amd64.tar.gz"
      sha256 "9c0228107295805b6812ef39337ce36894bd85158c023541fdf5ed1afca73ea6"

      define_method(:install) do
        bin.install "tofu-summary"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pablocolson/opentofu-summary/releases/download/v0.1.1/tofu-summary_0.1.1_darwin_arm64.tar.gz"
      sha256 "864b0ecba2cb953e2a5ae8579153891cb2c9367f241db401d1f8e0e76b16d384"

      define_method(:install) do
        bin.install "tofu-summary"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pablocolson/opentofu-summary/releases/download/v0.1.1/tofu-summary_0.1.1_linux_amd64.tar.gz"
      sha256 "c9e8155f0007471aa3e70d879d6a7d0b5ab9e5b7dc9151d8074cab8d4df725f5"
      define_method(:install) do
        bin.install "tofu-summary"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pablocolson/opentofu-summary/releases/download/v0.1.1/tofu-summary_0.1.1_linux_arm64.tar.gz"
      sha256 "0975f301f4ca63761f793fd36ac5199eca701da148c6d6898fc8be7e67dac055"
      define_method(:install) do
        bin.install "tofu-summary"
      end
    end
  end

  test do
    system "#{bin}/tofu-summary", "-version"
  end
end
